[Person]
model_name = "Person"
graphid = "22477f01-1a44-11e9-b0a9-000d3ab1e588"

[Group]
model_name = "Group"
graphid = "07883c9e-b25c-11e9-975a-a4d18cec433a"

[Set]
model_name = "Set"
graphid = "b16832e8-dfc9-4fc8-9c07-0c0b980ed220"

[Set.remapping]
title = "title.title_text"
members = "members"

["Logical Set"]
model_name = "Logical Set"
graphid = "5b8b4084-9687-11ee-8782-0242ac140006"
